export { SpecializedAnnexesForm } from './SpecializedAnnexesForm'
export { MidlineDeviationInput, CrowdingSpacingInput } from './orthodontics'
export { ClinicalHistoryForm, createEmptyClinicalForm } from './ClinicalHistoryForm'
export { MainHistoryForm } from './MainHistoryForm'
export { RapidValuationForm } from './RapidValuationForm'
export { ConsentimientoValoracionSection } from './ConsentimientoValoracionSection'
export { PatientRegistrationSection } from './PatientRegistrationSection'
export { AnamnesisForm } from './AnamnesisForm'
export { StomatologicalExamForm } from './StomatologicalExamForm'
export { EvolutionNotesForm } from './EvolutionNotesForm'
export { EvolutionNoteCard } from './EvolutionNoteCard'
export { EvolutionNoteAddendumPanel } from './EvolutionNoteAddendumPanel'
export { InformedConsentForm } from './InformedConsentForm'
export { ClinicalRecordList } from './ClinicalRecordList'
export { PatientIdentificationSummary } from './PatientIdentificationSummary'
