import { useEffect } from 'react'
import { Eye } from 'lucide-react'
import type {  OrthodonticsBudget,
  OrthodonticsPaymentRecord,
  OrthodonticsPaymentType,
  PaymentInvoice,
  PaymentMethod,
} from '@/types/clinicalRecord'
import { PAYMENT_METHOD_LABELS } from '@/constants/dental'
import {
  ORTHODONTICS_PAYMENT_TYPE_LABELS,
  buildOrthodonticsPaymentReason,
  calcOrthodonticsBudgetTotal,
  calcOrthodonticsInvoicedTotal,
  calcOrthodonticsPaymentsTotal,
  createEmptyOrthodonticsPayment,
  formatCurrency,
  generateId,
  getOrthodonticsControlNumbers,
  getPaidControlNumbers,
  hasInitialInstallmentPaid,
  orthodonticsPaymentBalance,
  suggestOrthodonticsPaymentAmount,
} from '@/utils'
import { useAuth } from '@/contexts/AuthContext'
import {
  clinicalPaymentsNeedAutoInvoices,
  ensureOrthodonticsPaymentsHaveAutoInvoices,
  syncAutoGeneratedInvoice,
} from '@/services/paymentInvoiceService'
import type { InvoiceViewMode } from '@/components/invoices/InvoiceViewModal'
import { paymentInvoiceStatusLabel } from '@/components/invoices/CreditNoteModal'
import {
  isPaymentInvoiceEditable,
  isPaymentInvoiceImmutable,
} from '@/services/invoiceImmutabilityService'

interface OrthodonticsPaymentControlFormProps {
  orthodonticsPaymentControl: OrthodonticsPaymentRecord[]
  orthodonticsBudget: OrthodonticsBudget
  disabled?: boolean
  patientName?: string
  patientDocument?: string
  onViewInvoice?: (view: InvoiceViewMode) => void
  onRequestCreditNote?: (paymentId: string, invoice: PaymentInvoice) => void
  onChange: (payments: OrthodonticsPaymentRecord[]) => void
}
const PAYMENT_METHODS = Object.keys(PAYMENT_METHOD_LABELS) as PaymentMethod[]

function emptyInvoice(): PaymentInvoice {
  return {
    id: generateId(),
    invoiceNumber: '',
    invoiceDate: new Date().toISOString().slice(0, 10),
    amount: 0,
  }
}

function applyPaymentTypeDefaults(
  payment: OrthodonticsPaymentRecord,
  paymentType: OrthodonticsPaymentType,
  budget: OrthodonticsBudget,
  controlNumber?: number,
  additionalDescription?: string,
): OrthodonticsPaymentRecord {
  const nextControl = paymentType === 'control' ? controlNumber ?? 1 : undefined
  const nextAdditional =
    paymentType === 'adicional' ? additionalDescription ?? payment.additionalPaymentDescription ?? '' : undefined

  return {
    ...payment,
    paymentType,
    controlNumber: nextControl,
    additionalPaymentDescription: nextAdditional,
    amount: suggestOrthodonticsPaymentAmount(paymentType, budget),
    paymentReason: buildOrthodonticsPaymentReason(
      paymentType,
      nextControl,
      nextAdditional,
    ),
  }
}

export function OrthodonticsPaymentControlForm({
  orthodonticsPaymentControl,
  orthodonticsBudget,
  disabled = false,
  patientName = '',
  patientDocument = '',
  onViewInvoice,
  onRequestCreditNote,
  onChange,
}: OrthodonticsPaymentControlFormProps) {  const { user } = useAuth()

  useEffect(() => {
    if (!clinicalPaymentsNeedAutoInvoices({ orthodonticsPaymentControl })) return
    onChange(ensureOrthodonticsPaymentsHaveAutoInvoices(orthodonticsPaymentControl, user?.id))
  }, [orthodonticsPaymentControl, user?.id, onChange])

  if (!orthodonticsBudget.active) return null

  const budgetTotal = calcOrthodonticsBudgetTotal(orthodonticsBudget)
  const totalPaid = calcOrthodonticsPaymentsTotal(orthodonticsPaymentControl)
  const totalInvoiced = calcOrthodonticsInvoicedTotal(orthodonticsPaymentControl)
  const balance = orthodonticsPaymentBalance(orthodonticsBudget, orthodonticsPaymentControl)
  const controlNumbers = getOrthodonticsControlNumbers(orthodonticsBudget)
  const paidControls = getPaidControlNumbers(orthodonticsPaymentControl)
  const initialPaid = hasInitialInstallmentPaid(orthodonticsPaymentControl)

  const updatePayment = (id: string, patch: Partial<OrthodonticsPaymentRecord>) => {
    onChange(
      orthodonticsPaymentControl.map((payment) => {
        if (payment.id !== id) return payment
        const merged = { ...payment, ...patch }
        if (patch.paymentType !== undefined || patch.controlNumber !== undefined) {
          return syncAutoGeneratedInvoice(
            applyPaymentTypeDefaults(
              merged,
              merged.paymentType,
              orthodonticsBudget,
              merged.controlNumber,
              merged.additionalPaymentDescription,
            ),
          )
        }
        if (patch.additionalPaymentDescription !== undefined) {
          return syncAutoGeneratedInvoice({
            ...merged,
            paymentReason: buildOrthodonticsPaymentReason(
              merged.paymentType,
              merged.controlNumber,
              merged.additionalPaymentDescription,
            ),
          })
        }
        return syncAutoGeneratedInvoice(merged)
      }),
    )
  }

  const removePayment = (id: string) => {
    onChange(orthodonticsPaymentControl.filter((p) => p.id !== id))
  }

  const addPayment = () => {
    const defaultType: OrthodonticsPaymentType = initialPaid ? 'control' : 'cuota_inicial'
    onChange([
      ...orthodonticsPaymentControl,
      createEmptyOrthodonticsPayment(orthodonticsBudget, defaultType, user?.id),
    ])
  }

  const addInvoice = (paymentId: string) => {
    onChange(
      orthodonticsPaymentControl.map((p) =>
        p.id === paymentId ? { ...p, invoices: [...p.invoices, emptyInvoice()] } : p,
      ),
    )
  }

  const updateInvoice = (
    paymentId: string,
    invoiceId: string,
    patch: Partial<PaymentInvoice>,
  ) => {
    onChange(
      orthodonticsPaymentControl.map((p) =>
        p.id === paymentId
          ? {
              ...p,
              invoices: p.invoices.map((inv) => {
                if (inv.id !== invoiceId) return inv
                if (!isPaymentInvoiceEditable(inv)) return inv
                return { ...inv, ...patch }
              }),
            }
          : p,
      ),
    )
  }

  return (
    <div className="mt-6 rounded-lg border border-dental-200 bg-dental-50/40 p-4">
      <h4 className="mb-1 text-sm font-semibold text-dental-800">
        Control de pagos — Ortodoncia
      </h4>
      <p className="mb-4 text-xs text-slate-600">
        Registre cuota inicial, controles según presupuesto, retenedores o pagos adicionales. Cada
        pago genera automáticamente su factura con consecutivo.
      </p>

      <div className="mb-4 grid gap-3 rounded-lg border border-dental-100 bg-white p-3 sm:grid-cols-4">
        <div>
          <span className="text-xs text-slate-500">Presupuesto ortodoncia</span>
          <p className="font-semibold text-slate-800">{formatCurrency(budgetTotal)}</p>
        </div>
        <div>
          <span className="text-xs text-slate-500">Pagado ortodoncia</span>
          <p className="font-semibold text-green-700">{formatCurrency(totalPaid)}</p>
        </div>
        <div>
          <span className="text-xs text-slate-500">Saldo ortodoncia</span>
          <p className="font-semibold text-amber-700">{formatCurrency(balance)}</p>
        </div>
        <div>
          <span className="text-xs text-slate-500">Facturado ortodoncia</span>
          <p className="font-semibold text-slate-800">{formatCurrency(totalInvoiced)}</p>
        </div>
      </div>

      {controlNumbers.length > 0 && (
        <p className="mb-3 text-xs text-slate-500">
          Controles presupuestados: {controlNumbers.length}
          {paidControls.length > 0 && (
            <span className="ml-2">
              · Pagados: {paidControls.sort((a, b) => a - b).join(', ')}
            </span>
          )}
        </p>
      )}

      {!disabled && (
        <div className="mb-4">
          <button type="button" onClick={addPayment} className="btn-secondary text-xs">
            + Registrar pago ortodoncia
          </button>
        </div>
      )}

      {orthodonticsPaymentControl.length === 0 ? (
        <p className="text-sm text-slate-500">No hay pagos de ortodoncia registrados.</p>
      ) : (
        <div className="space-y-4">
          {orthodonticsPaymentControl.map((payment, index) => (
            <div key={payment.id} className="rounded-lg border border-slate-200 bg-white p-4">
              <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                <h5 className="font-medium text-slate-800">Pago ortodoncia #{index + 1}</h5>
                <span className="text-sm font-semibold text-dental-700">
                  {formatCurrency(payment.amount)}
                </span>
              </div>

              <div className="grid gap-3 sm:grid-cols-12">
                <div className="sm:col-span-3">
                  <label className="mb-0.5 block text-[10px] text-slate-500">Fecha de pago</label>
                  <input
                    type="date"
                    disabled={disabled}
                    value={payment.paymentDate}
                    onChange={(e) => updatePayment(payment.id, { paymentDate: e.target.value })}
                    className="input-field"
                  />
                </div>
                <div className="sm:col-span-3">
                  <label className="mb-0.5 block text-[10px] text-slate-500">Tipo de pago</label>
                  <select
                    disabled={disabled}
                    value={payment.paymentType}
                    onChange={(e) =>
                      updatePayment(payment.id, {
                        paymentType: e.target.value as OrthodonticsPaymentType,
                      })
                    }
                    className="input-field text-sm"
                  >
                    {(Object.keys(ORTHODONTICS_PAYMENT_TYPE_LABELS) as OrthodonticsPaymentType[]).map(
                      (type) => (
                        <option key={type} value={type}>
                          {ORTHODONTICS_PAYMENT_TYPE_LABELS[type]}
                        </option>
                      ),
                    )}
                  </select>
                </div>

                {payment.paymentType === 'control' && (
                  <div className="sm:col-span-2">
                    <label className="mb-0.5 block text-[10px] text-slate-500">
                      Nº de control
                    </label>
                    <select
                      disabled={disabled || controlNumbers.length === 0}
                      value={payment.controlNumber ?? 1}
                      onChange={(e) =>
                        updatePayment(payment.id, { controlNumber: Number(e.target.value) })
                      }
                      className="input-field text-sm"
                    >
                      {controlNumbers.length === 0 ? (
                        <option value={1}>Sin controles en presupuesto</option>
                      ) : (
                        controlNumbers.map((num) => (
                          <option key={num} value={num}>
                            Control #{num}
                            {paidControls.includes(num) &&
                            orthodonticsPaymentControl.some(
                              (p) =>
                                p.id !== payment.id &&
                                p.paymentType === 'control' &&
                                p.controlNumber === num,
                            )
                              ? ' (ya pagado)'
                              : ''}
                          </option>
                        ))
                      )}
                    </select>
                  </div>
                )}

                <div className={payment.paymentType === 'control' ? 'sm:col-span-2' : 'sm:col-span-3'}>
                  <label className="mb-0.5 block text-[10px] text-slate-500">Valor pagado</label>
                  <input
                    type="number"
                    min={0}
                    disabled={disabled}
                    value={payment.amount}
                    onChange={(e) => updatePayment(payment.id, { amount: Number(e.target.value) })}
                    className="input-field"
                  />
                </div>
                <div className={payment.paymentType === 'control' ? 'sm:col-span-2' : 'sm:col-span-3'}>
                  <label className="mb-0.5 block text-[10px] text-slate-500">Forma de pago</label>
                  <select
                    disabled={disabled}
                    value={payment.paymentMethod}
                    onChange={(e) =>
                      updatePayment(payment.id, {
                        paymentMethod: e.target.value as PaymentMethod,
                      })
                    }
                    className="input-field text-sm"
                  >
                    {PAYMENT_METHODS.map((method) => (
                      <option key={method} value={method}>
                        {PAYMENT_METHOD_LABELS[method]}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {payment.paymentType === 'adicional' && (
                <div className="mt-3">
                  <label className="mb-0.5 block text-xs font-medium text-slate-700">
                    Especificación del pago adicional <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    rows={2}
                    disabled={disabled}
                    value={payment.additionalPaymentDescription ?? ''}
                    onChange={(e) =>
                      updatePayment(payment.id, {
                        additionalPaymentDescription: e.target.value,
                      })
                    }
                    placeholder="Ej.: Reparación de bracket, cambio de arco, kit de higiene..."
                    className="input-field resize-y text-sm"
                  />
                </div>
              )}

              <div className="mt-3">
                <label className="mb-0.5 block text-xs font-medium text-slate-700">
                  Motivo del pago
                </label>
                <textarea
                  rows={2}
                  disabled={disabled}
                  value={payment.paymentReason}
                  onChange={(e) => updatePayment(payment.id, { paymentReason: e.target.value })}
                  className="input-field resize-y text-sm"
                />
              </div>

              <div className="mt-4 rounded-lg border border-dashed border-slate-200 bg-slate-50/60 p-3">
                <div className="mb-2 flex items-center justify-between gap-2">
                  <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Facturas del pago
                  </span>
                  {!disabled && (
                    <button
                      type="button"
                      onClick={() => addInvoice(payment.id)}
                      className="text-xs font-medium text-dental-600 hover:text-dental-800"
                    >
                      + Agregar factura
                    </button>
                  )}
                </div>

                {payment.invoices.length === 0 ? (
                  <p className="text-xs text-slate-500">Sin facturas asociadas a este pago.</p>
                ) : (
                  <div className="space-y-2">
                    {payment.invoices.map((invoice) => {
                      const voidedLabel = paymentInvoiceStatusLabel(invoice)
                      const invoiceLocked = disabled || !isPaymentInvoiceEditable(invoice)
                      const canCreditNote =
                        isPaymentInvoiceImmutable(invoice) &&
                        invoice.status !== 'voided_by_credit_note'

                      return (
                      <div
                        key={invoice.id}
                        className="grid gap-2 rounded-md border border-slate-200 bg-white p-2 sm:grid-cols-12"
                      >
                        {voidedLabel && (
                          <div className="sm:col-span-12">
                            <span className="inline-flex rounded-full bg-rose-100 px-2.5 py-0.5 text-xs font-medium text-rose-800">
                              {voidedLabel}
                            </span>
                          </div>
                        )}
                        <div className="sm:col-span-3">
                          <label className="mb-0.5 block text-[10px] text-slate-500">
                            Nº factura
                          </label>
                          {invoice.autoGenerated && !disabled && (
                            <span className="mb-1 inline-flex rounded-full bg-dental-100 px-2 py-0.5 text-[10px] font-medium text-dental-800">
                              Automática
                            </span>
                          )}
                          <input
                            disabled={invoiceLocked}
                            value={invoice.invoiceNumber}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, {
                                invoiceNumber: e.target.value,
                              })
                            }
                            placeholder="Ej. FV-00125"
                            className="input-field font-mono text-sm"
                          />
                        </div>
                        <div className="sm:col-span-2">
                          <label className="mb-0.5 block text-[10px] text-slate-500">Fecha</label>
                          <input
                            type="date"
                            disabled={invoiceLocked}
                            value={invoice.invoiceDate}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, {
                                invoiceDate: e.target.value,
                              })
                            }
                            className="input-field"
                          />
                        </div>
                        <div className="sm:col-span-2">
                          <label className="mb-0.5 block text-[10px] text-slate-500">Valor</label>
                          <input
                            type="number"
                            min={0}
                            disabled={invoiceLocked}
                            value={invoice.amount}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, {
                                amount: Number(e.target.value),
                              })
                            }
                            className="input-field"
                          />
                        </div>
                        <div className="sm:col-span-4">
                          <label className="mb-0.5 block text-[10px] text-slate-500">
                            Observaciones
                          </label>
                          <input
                            disabled={invoiceLocked}
                            value={invoice.notes ?? ''}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, { notes: e.target.value })
                            }
                            placeholder="Opcional"
                            className="input-field text-sm"
                          />
                        </div>
                        <div className="flex flex-wrap items-end justify-end gap-2 sm:col-span-12">
                          <button
                            type="button"
                            onClick={() =>
                              onViewInvoice?.({
                                kind: 'payment',
                                invoice,
                                patientName,
                                patientDocument,
                                paymentReason: payment.paymentReason,
                                paymentMethodLabel: PAYMENT_METHOD_LABELS[payment.paymentMethod],
                              })
                            }
                            className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700 hover:bg-slate-50"
                          >
                            <Eye className="h-3.5 w-3.5" />
                            Ver factura
                          </button>
                          {canCreditNote && (
                            <button
                              type="button"
                              onClick={() => onRequestCreditNote?.(payment.id, invoice)}
                              className="inline-flex items-center gap-1 rounded-lg border border-rose-200 bg-rose-50 px-2.5 py-1 text-xs font-medium text-rose-800 hover:bg-rose-100"
                            >
                              Anular con Nota Crédito
                            </button>
                          )}
                        </div>
                      </div>
                    )})}
                  </div>
                )}
              </div>

              {!disabled && (
                <div className="mt-3 text-right">
                  <button
                    type="button"
                    onClick={() => removePayment(payment.id)}
                    className="text-sm text-red-500 hover:text-red-700"
                  >
                    Eliminar pago
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
