import { useEffect, useMemo, useState } from 'react'
import { Eye, Printer } from 'lucide-react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from '@/db/database'
import type { UserProfile } from '@/types/user'
import type {
  BudgetSummary,
  OrthodonticsBudget,
  OrthodonticsPaymentRecord,
  PaymentInvoice,
  PaymentMethod,
  PaymentPlanItem,
  PaymentRecord,
} from '@/types/clinicalRecord'
import { PAYMENT_METHOD_LABELS } from '@/constants/dental'
import {
  CLINICAL_HISTORY_SECTION_NUMBERS,
  CLINICAL_SECTION_TITLE_CLASS,
  clinicalSectionTitle,
} from '@/constants/clinicalHistorySections'
import {
  calcTotalInvoiced,
  calcTotalPaid,
  formatCurrency,
  generateId,
} from '@/utils'
import { OrthodonticsPaymentControlForm } from './OrthodonticsPaymentControlForm'
import { PaymentMotivoValorFields } from './PaymentMotivoValorFields'
import { useAuth } from '@/contexts/AuthContext'
import { useTariffSync } from '@/modules/tariff/useTariffSync'
import {
  attachAutoInvoiceToPayment,
  clinicalPaymentsNeedAutoInvoices,
  ensurePaymentsHaveAutoInvoices,
  paymentNeedsAutoInvoice,
  syncAutoGeneratedInvoice,
} from '@/services/paymentInvoiceService'
import { InvoiceViewModal, type InvoiceViewMode } from '@/components/invoices/InvoiceViewModal'
import { emitChargeReceipt } from '@/services/chargeEmissionService'
import { printThermalReceipt, buildThermalDataFromPayment } from '@/utils/thermalInvoicePrint'
import { CreditNoteModal, paymentInvoiceStatusLabel } from '@/components/invoices/CreditNoteModal'
import { FolioRechargeModal } from '@/components/invoices/FolioRechargeModal'
import { FOLIO_DEPLETED_MESSAGE } from '@/types/billingModality'
import {
  BILLING_SETTINGS_CHANGED_EVENT,
  getFolioBalanceLabel,
  getFoliosAvailable,
  usesProviderEmission,
} from '@/services/billingModalityService'
import {
  createCreditNoteForPaymentInvoice,
  voidPaymentInvoiceLocally,
} from '@/services/creditNoteService'
import {
  isPaymentInvoiceEditable,
  isPaymentInvoiceImmutable,
} from '@/services/invoiceImmutabilityService'
import { ROLE_LABELS } from '@/utils/permissions'

interface PaymentControlFormProps {
  paymentControl: PaymentRecord[]
  orthodonticsPaymentControl: OrthodonticsPaymentRecord[]
  orthodonticsBudget?: OrthodonticsBudget
  paymentPlan: PaymentPlanItem[]
  budget: BudgetSummary
  disabled?: boolean
  patientId?: string
  clinicalRecordId?: string | number
  patientName?: string
  patientDocument?: string
  onChange: (paymentControl: PaymentRecord[]) => void
  onOrthodonticsPaymentControlChange: (payments: OrthodonticsPaymentRecord[]) => void
}

const PAYMENT_METHODS = Object.keys(PAYMENT_METHOD_LABELS) as PaymentMethod[]

function formatTreatingDentistName(user: UserProfile): string {
  return `${user.firstName} ${user.lastName}`.trim()
}

function formatTreatingDentistOption(user: UserProfile): string {
  const name = formatTreatingDentistName(user)
  const document = user.documentNumber?.trim()
  const role = ROLE_LABELS[user.role as keyof typeof ROLE_LABELS] ?? user.role
  const details = [document, role].filter(Boolean).join(' · ')
  return details ? `${name} — ${details}` : name
}

function emptyPayment(user?: UserProfile): PaymentRecord {
  return attachAutoInvoiceToPayment(
    {
      id: generateId(),
      paymentDate: new Date().toISOString().slice(0, 10),
      amount: 0,
      paymentMethod: 'contado',
      paymentReason: '',
      treatingDentistUserId: user?.id,
      treatingDentistName: user ? formatTreatingDentistName(user) : undefined,
      invoices: [],
    },
    user?.id,
  )
}

function emptyInvoice(): PaymentInvoice {
  return {
    id: generateId(),
    invoiceNumber: '',
    invoiceDate: new Date().toISOString().slice(0, 10),
    amount: 0,
  }
}

export function PaymentControlForm({
  paymentControl,
  orthodonticsPaymentControl,
  orthodonticsBudget,
  paymentPlan,
  budget,
  disabled = false,
  patientId = '',
  clinicalRecordId,
  patientName = '',
  patientDocument = '',
  onChange,
  onOrthodonticsPaymentControlChange,
}: PaymentControlFormProps) {
  const { user } = useAuth()
  useTariffSync(user?.id)
  const appUsers = useLiveQuery(() => db.users.toArray(), []) ?? []

  const treatingDentists = useMemo(
    () =>
      [...appUsers].sort((a, b) =>
        formatTreatingDentistName(a).localeCompare(formatTreatingDentistName(b), 'es'),
      ),
    [appUsers],
  )
  const [invoiceView, setInvoiceView] = useState<InvoiceViewMode | null>(null)
  const [creditNoteTarget, setCreditNoteTarget] = useState<{
    paymentId: string
    invoice: PaymentInvoice
    source: 'control' | 'orthodontics'
  } | null>(null)
  const [creditNoteBusy, setCreditNoteBusy] = useState(false)
  const [creditNoteMessage, setCreditNoteMessage] = useState<string | null>(null)
  const [chargeBusyId, setChargeBusyId] = useState<string | null>(null)
  const [chargeMessage, setChargeMessage] = useState<string | null>(null)
  const [chargeDepleted, setChargeDepleted] = useState(false)
  const [rechargeOpen, setRechargeOpen] = useState(false)
  const [folioLabel, setFolioLabel] = useState(() => getFolioBalanceLabel())
  const [hasElectronicFolios, setHasElectronicFolios] = useState(() => usesProviderEmission())
  const totalPaid = calcTotalPaid(paymentControl)

  useEffect(() => {
    const refreshFolios = () => {
      setFolioLabel(getFolioBalanceLabel())
      setHasElectronicFolios(usesProviderEmission())
    }
    window.addEventListener(BILLING_SETTINGS_CHANGED_EVENT, refreshFolios)
    return () => window.removeEventListener(BILLING_SETTINGS_CHANGED_EVENT, refreshFolios)
  }, [])

  useEffect(() => {
    if (!clinicalPaymentsNeedAutoInvoices({ paymentControl })) return
    onChange(ensurePaymentsHaveAutoInvoices(paymentControl, user?.id))
  }, [paymentControl, user?.id, onChange])

  const totalInvoiced = calcTotalInvoiced(paymentControl)
  const balance = Math.max(0, budget.total - totalPaid)

  const updatePayment = (id: string, patch: Partial<PaymentRecord>) => {
    onChange(
      paymentControl.map((payment) => {
        if (payment.id !== id) return payment
        const next = syncAutoGeneratedInvoice({ ...payment, ...patch })
        return paymentNeedsAutoInvoice(next)
          ? attachAutoInvoiceToPayment(next, user?.id)
          : next
      }),
    )
  }

  const removePayment = (id: string) => {
    onChange(paymentControl.filter((p) => p.id !== id))
  }

  const addPayment = () => {
    onChange([...paymentControl, emptyPayment(user ?? undefined)])
  }

  const updateTreatingDentist = (paymentId: string, dentistUserId: string) => {
    const selected = treatingDentists.find((item) => item.id === dentistUserId)
    updatePayment(paymentId, {
      treatingDentistUserId: dentistUserId || undefined,
      treatingDentistName: selected ? formatTreatingDentistName(selected) : undefined,
    })
  }

  const patchPaymentInvoice = (paymentId: string, invoiceId: string, next: PaymentInvoice) => {
    onChange(
      paymentControl.map((payment) =>
        payment.id === paymentId
          ? {
              ...payment,
              invoices: payment.invoices.map((invoice) =>
                invoice.id === invoiceId ? next : invoice,
              ),
            }
          : payment,
      ),
    )
  }

  const handleChargeAndPrint = async (payment: PaymentRecord, forceCashReceipt = false) => {
    const invoice = payment.invoices.find((item) => item.autoGenerated) ?? payment.invoices[0]
    if (!invoice || payment.amount <= 0) return
    setChargeBusyId(payment.id)
    setChargeMessage(null)
    setChargeDepleted(false)
    try {
      const result = await emitChargeReceipt({
        invoice,
        patientName,
        patientDocument,
        paymentReason: payment.paymentReason,
        cupsCode: payment.cupsCode,
        amount: payment.amount,
        forceCashReceipt,
      })
      patchPaymentInvoice(payment.id, invoice.id, result.invoice)
      setChargeMessage(result.message)
      setChargeDepleted(result.depleted)
      setFolioLabel(getFolioBalanceLabel())
      setHasElectronicFolios(usesProviderEmission())
      const thermal = buildThermalDataFromPayment({
        invoice: result.invoice,
        patientName,
        patientDocument,
        paymentReason: payment.paymentReason,
        paymentMethodLabel: PAYMENT_METHOD_LABELS[payment.paymentMethod],
        treatingDentistName: payment.treatingDentistName,
      })
      await printThermalReceipt(thermal)
      setInvoiceView({
        kind: 'payment',
        invoice: result.invoice,
        patientName,
        patientDocument,
        paymentReason: payment.paymentReason,
        paymentMethodLabel: PAYMENT_METHOD_LABELS[payment.paymentMethod],
        treatingDentistName: payment.treatingDentistName,
      })
    } catch (error) {
      setChargeMessage(error instanceof Error ? error.message : 'No se pudo cobrar e imprimir.')
    } finally {
      setChargeBusyId(null)
    }
  }

  const addInvoice = (paymentId: string) => {
    onChange(
      paymentControl.map((p) =>
        p.id === paymentId ? { ...p, invoices: [...p.invoices, emptyInvoice()] } : p,
      ),
    )
  }

  const updateInvoice = (
    paymentId: string,
    invoiceId: string,
    patch: Partial<PaymentInvoice>,
  ) => {
    onChange(
      paymentControl.map((p) =>
        p.id === paymentId
          ? {
              ...p,
              invoices: p.invoices.map((inv) => {
                if (inv.id !== invoiceId) return inv
                if (!isPaymentInvoiceEditable(inv)) return inv
                return { ...inv, ...patch }
              }),
            }
          : p,
      ),
    )
  }

  const applyVoidedPaymentInvoice = (
    paymentId: string,
    invoiceId: string,
    voided: PaymentInvoice,
    source: 'control' | 'orthodontics',
  ) => {
    if (source === 'control') {
      onChange(
        paymentControl.map((payment) =>
          payment.id === paymentId
            ? {
                ...payment,
                invoices: payment.invoices.map((invoice) =>
                  invoice.id === invoiceId ? voided : invoice,
                ),
              }
            : payment,
        ),
      )
      return
    }

    onOrthodonticsPaymentControlChange(
      orthodonticsPaymentControl.map((payment) =>
        payment.id === paymentId
          ? {
              ...payment,
              invoices: payment.invoices.map((invoice) =>
                invoice.id === invoiceId ? voided : invoice,
              ),
            }
          : payment,
      ),
    )
  }

  const handleCreditNoteSubmit = async (reason: string) => {
    if (!creditNoteTarget || !user || !patientId) return
    setCreditNoteBusy(true)
    setCreditNoteMessage(null)
    try {
      const creditNote = await createCreditNoteForPaymentInvoice({
        paymentInvoice: creditNoteTarget.invoice,
        reason,
        professional: user,
        patientId,
        clinicalRecordId,
      })
      const voided = voidPaymentInvoiceLocally(creditNoteTarget.invoice, creditNote)
      applyVoidedPaymentInvoice(
        creditNoteTarget.paymentId,
        creditNoteTarget.invoice.id,
        voided,
        creditNoteTarget.source,
      )
      setCreditNoteMessage(`Nota Crédito ${creditNote.creditNoteNumber} emitida correctamente.`)
      setCreditNoteTarget(null)
    } catch (error) {
      setCreditNoteMessage(
        error instanceof Error ? error.message : 'No se pudo generar la Nota Crédito.',
      )
    } finally {
      setCreditNoteBusy(false)
    }
  }

  return (
    <section className="card">
      <h3 className={`mb-2 ${CLINICAL_SECTION_TITLE_CLASS}`}>
        {clinicalSectionTitle(
          CLINICAL_HISTORY_SECTION_NUMBERS.controlPagos,
          'Control de Pagos',
        )}
      </h3>
      <p className="mb-4 text-xs text-slate-500">
        Registre cada pago recibido con su motivo y valor. Puede autocargarlos desde un código CUPS
        del tarifario o definirlos manualmente. Al crear un pago se genera automáticamente una
        factura con consecutivo asignado. El Recibo de Caja interno de 80 mm no consume folios.
      </p>

      {getFoliosAvailable() <= 0 && (
        <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950">
          <p>{FOLIO_DEPLETED_MESSAGE}</p>
          <button
            type="button"
            className="mt-2 text-sm font-semibold text-dental-800 underline"
            onClick={() => setRechargeOpen(true)}
          >
            Recargar Paquete de Facturas
          </button>
        </div>
      )}
      <p className="mb-3 text-xs font-medium text-slate-600">{folioLabel}</p>

      <div className="mb-4 grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 sm:grid-cols-4">
        <div>
          <span className="text-xs text-slate-500">Total presupuesto</span>
          <p className="font-semibold text-slate-800">{formatCurrency(budget.total)}</p>
        </div>
        <div>
          <span className="text-xs text-slate-500">Total pagado</span>
          <p className="font-semibold text-green-700">{formatCurrency(totalPaid)}</p>
        </div>
        <div>
          <span className="text-xs text-slate-500">Saldo pendiente</span>
          <p className="font-semibold text-amber-700">{formatCurrency(balance)}</p>
        </div>
        <div>
          <span className="text-xs text-slate-500">Total facturado</span>
          <p className="font-semibold text-slate-800">{formatCurrency(totalInvoiced)}</p>
        </div>
      </div>

      {!disabled && (
        <div className="mb-4 rounded-xl border border-green-200 bg-green-50 p-4">
          <button
            type="button"
            onClick={addPayment}
            className="inline-flex items-center justify-center rounded-lg border border-green-600 bg-green-600 px-6 py-3 text-base font-semibold text-white shadow-sm transition hover:bg-green-700 hover:border-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
          >
            + Registrar Nuevo Pago
          </button>
        </div>
      )}

      {paymentControl.length === 0 ? (
        <p className="text-sm text-slate-500">
          No hay pagos registrados. Agregue un pago con el botón superior.
        </p>
      ) : (
        <div className="space-y-4">
          {paymentControl.map((payment, index) => (
            <div
              key={payment.id}
              className="rounded-xl border border-green-200 bg-green-50 p-4"
            >
              <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                <h4 className="font-medium text-slate-800">Pago #{index + 1}</h4>
                <span className="text-sm font-semibold text-dental-700">
                  {formatCurrency(payment.amount)}
                </span>
              </div>

              <div className="grid gap-3 sm:grid-cols-12">
                <div className="sm:col-span-4">
                  <label className="mb-0.5 block text-[10px] text-slate-500">Fecha de pago</label>
                  <input
                    type="date"
                    disabled={disabled}
                    value={payment.paymentDate}
                    onChange={(e) => updatePayment(payment.id, { paymentDate: e.target.value })}
                    className="input-field"
                  />
                </div>
                <div className="sm:col-span-4">
                  <label className="mb-0.5 block text-[10px] text-slate-500">Forma de pago</label>
                  <select
                    disabled={disabled}
                    value={payment.paymentMethod}
                    onChange={(e) =>
                      updatePayment(payment.id, {
                        paymentMethod: e.target.value as PaymentMethod,
                      })
                    }
                    className="input-field text-sm"
                  >
                    {PAYMENT_METHODS.map((method) => (
                      <option key={method} value={method}>
                        {PAYMENT_METHOD_LABELS[method]}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="sm:col-span-4">
                  <label className="mb-0.5 block text-[10px] text-slate-500">
                    Vínculo plan de pagos
                  </label>
                  <select
                    disabled={disabled}
                    value={payment.paymentPlanItemId ?? ''}
                    onChange={(e) =>
                      updatePayment(payment.id, {
                        paymentPlanItemId: e.target.value || undefined,
                      })
                    }
                    className="input-field text-sm"
                  >
                    <option value="">Sin vínculo</option>
                    {paymentPlan.map((item) => (
                      <option key={item.id} value={item.id}>
                        {item.procedure || 'Sin nombre'} — {formatCurrency(item.totalAmount)}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="mt-3 grid gap-3 sm:grid-cols-12">
                <div className="sm:col-span-6">
                  <label className="mb-0.5 block text-[10px] text-slate-500">
                    Odontólogo tratante <span className="text-red-500">*</span>
                  </label>
                  {disabled ? (
                    <p className="text-sm text-slate-800">{payment.treatingDentistName || '—'}</p>
                  ) : (
                    <select
                      value={payment.treatingDentistUserId ?? ''}
                      onChange={(event) => updateTreatingDentist(payment.id, event.target.value)}
                      className="input-field text-sm"
                    >
                      <option value="">Seleccionar odontólogo...</option>
                      {treatingDentists.map((dentist) => (
                        <option key={dentist.id} value={dentist.id}>
                          {formatTreatingDentistOption(dentist)}
                        </option>
                      ))}
                    </select>
                  )}
                </div>
              </div>

              <PaymentMotivoValorFields
                cupsCode={payment.cupsCode}
                paymentReason={payment.paymentReason}
                amount={payment.amount}
                disabled={disabled}
                onChange={(patch) => updatePayment(payment.id, patch)}
              />

              <div className="mt-4 rounded-lg border border-dashed border-slate-200 bg-slate-50/60 p-3">
                <div className="mb-2 flex items-center justify-between gap-2">
                  <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Facturas del pago
                  </span>
                  {!disabled && (
                    <button
                      type="button"
                      onClick={() => addInvoice(payment.id)}
                      className="text-xs font-medium text-dental-600 hover:text-dental-800"
                    >
                      + Agregar factura
                    </button>
                  )}
                </div>

                {payment.invoices.length === 0 ? (
                  <p className="text-xs text-slate-500">Sin facturas asociadas a este pago.</p>
                ) : (
                  <div className="space-y-2">
                    {payment.invoices.map((invoice) => {
                      const voidedLabel = paymentInvoiceStatusLabel(invoice)
                      const invoiceLocked = disabled || !isPaymentInvoiceEditable(invoice)
                      const canCreditNote =
                        isPaymentInvoiceImmutable(invoice) &&
                        invoice.status !== 'voided_by_credit_note'

                      return (
                      <div
                        key={invoice.id}
                        className="grid gap-2 rounded-md border border-slate-200 bg-white p-2 sm:grid-cols-12"
                      >
                        {voidedLabel && (
                          <div className="sm:col-span-12">
                            <span className="inline-flex rounded-full bg-rose-100 px-2.5 py-0.5 text-xs font-medium text-rose-800">
                              {voidedLabel}
                            </span>
                          </div>
                        )}
                        <div className="sm:col-span-3">
                          <label className="mb-0.5 block text-[10px] text-slate-500">
                            Nº factura
                          </label>
                          {invoice.autoGenerated && !disabled && (
                            <span className="mb-1 inline-flex rounded-full bg-dental-100 px-2 py-0.5 text-[10px] font-medium text-dental-800">
                              Automática
                            </span>
                          )}
                          {invoiceLocked ? (
                            <span className="font-mono text-sm">{invoice.invoiceNumber || '—'}</span>
                          ) : (
                            <input
                              value={invoice.invoiceNumber}
                              onChange={(e) =>
                                updateInvoice(payment.id, invoice.id, {
                                  invoiceNumber: e.target.value,
                                })
                              }
                              placeholder="Ej. FV-00125"
                              className="input-field font-mono text-sm"
                            />
                          )}
                        </div>
                        <div className="sm:col-span-2">
                          <label className="mb-0.5 block text-[10px] text-slate-500">Fecha</label>
                          <input
                            type="date"
                            disabled={invoiceLocked}
                            value={invoice.invoiceDate}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, {
                                invoiceDate: e.target.value,
                              })
                            }
                            className="input-field"
                          />
                        </div>
                        <div className="sm:col-span-2">
                          <label className="mb-0.5 block text-[10px] text-slate-500">Valor</label>
                          <input
                            type="number"
                            min={0}
                            disabled={invoiceLocked}
                            value={invoice.amount}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, {
                                amount: Number(e.target.value),
                              })
                            }
                            className="input-field"
                          />
                        </div>
                        <div className="sm:col-span-4">
                          <label className="mb-0.5 block text-[10px] text-slate-500">
                            Observaciones
                          </label>
                          <input
                            disabled={invoiceLocked}
                            value={invoice.notes ?? ''}
                            onChange={(e) =>
                              updateInvoice(payment.id, invoice.id, { notes: e.target.value })
                            }
                            placeholder="Opcional"
                            className="input-field text-sm"
                          />
                        </div>
                        <div className="flex flex-wrap items-end justify-end gap-2 sm:col-span-12">
                          <button
                            type="button"
                            disabled={Boolean(chargeBusyId) || payment.amount <= 0}
                            onClick={() => void handleChargeAndPrint(payment)}
                            className="inline-flex items-center gap-1 rounded-lg bg-green-700 px-2.5 py-1 text-xs font-medium text-white hover:bg-green-800 disabled:opacity-50"
                          >
                            <Printer className="h-3.5 w-3.5" />
                            {chargeBusyId === payment.id
                              ? 'Cobrando…'
                              : hasElectronicFolios
                                ? 'Cobrar e imprimir'
                                : 'Cobrar Recibo de Caja'}
                          </button>
                          <button
                            type="button"
                            disabled={Boolean(chargeBusyId) || payment.amount <= 0}
                            onClick={() => void handleChargeAndPrint(payment, true)}
                            className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-2.5 py-1 text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
                          >
                            Recibo de Caja interno 80 mm ($0)
                          </button>
                          <button
                            type="button"
                            onClick={() =>
                              setInvoiceView({
                                kind: 'payment',
                                invoice,
                                patientName,
                                patientDocument,
                                paymentReason: payment.paymentReason,
                                paymentMethodLabel: PAYMENT_METHOD_LABELS[payment.paymentMethod],
                                treatingDentistName: payment.treatingDentistName,
                              })
                            }
                            className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700 hover:bg-slate-50"
                          >
                            <Eye className="h-3.5 w-3.5" />
                            Ver factura
                          </button>
                          {canCreditNote && (
                            <button
                              type="button"
                              onClick={() =>
                                setCreditNoteTarget({
                                  paymentId: payment.id,
                                  invoice,
                                  source: 'control',
                                })
                              }
                              className="inline-flex items-center gap-1 rounded-lg border border-rose-200 bg-rose-50 px-2.5 py-1 text-xs font-medium text-rose-800 hover:bg-rose-100"
                            >
                              Anular con Nota Crédito
                            </button>
                          )}
                        </div>
                      </div>
                    )})}
                  </div>
                )}
              </div>

              {!disabled && (
                <div className="mt-3 text-right">
                  <button
                    type="button"
                    onClick={() => removePayment(payment.id)}
                    className="text-sm text-red-500 hover:text-red-700"
                  >
                    Eliminar pago
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {orthodonticsBudget?.active && (
        <OrthodonticsPaymentControlForm
          orthodonticsPaymentControl={orthodonticsPaymentControl}
          orthodonticsBudget={orthodonticsBudget}
          disabled={disabled}
          patientName={patientName}
          patientDocument={patientDocument}
          onViewInvoice={setInvoiceView}
          onRequestCreditNote={(paymentId, invoice) =>
            setCreditNoteTarget({ paymentId, invoice, source: 'orthodontics' })
          }
          onChange={onOrthodonticsPaymentControlChange}
        />
      )}
      {chargeMessage && (
        <p
          className={`mt-3 rounded-lg border px-3 py-2 text-sm ${
            chargeDepleted || chargeMessage === FOLIO_DEPLETED_MESSAGE
              ? 'border-amber-200 bg-amber-50 text-amber-950'
              : 'border-green-200 bg-green-50 text-green-900'
          }`}
        >
          {chargeMessage}
        </p>
      )}
      {creditNoteMessage && (
        <p className="mt-3 rounded-lg border border-dental-200 bg-dental-50 px-3 py-2 text-sm text-dental-900">
          {creditNoteMessage}
        </p>
      )}
      <CreditNoteModal
        open={creditNoteTarget != null}
        invoiceNumber={creditNoteTarget?.invoice.invoiceNumber ?? ''}
        amount={creditNoteTarget?.invoice.amount}
        busy={creditNoteBusy}
        onClose={() => setCreditNoteTarget(null)}
        onSubmit={handleCreditNoteSubmit}
      />
      <InvoiceViewModal view={invoiceView} onClose={() => setInvoiceView(null)} />
      <FolioRechargeModal
        open={rechargeOpen}
        onClose={() => setRechargeOpen(false)}
        onPurchased={() => {
          setFolioLabel(getFolioBalanceLabel())
          setHasElectronicFolios(usesProviderEmission())
        }}
      />
    </section>
  )
}
