import type { PaymentInvoice } from '@/types/clinicalRecord'
import type { ElectronicInvoice, InvoiceStatus } from '@/types/invoice'
import { CREDIT_NOTE_IMMUTABILITY_MESSAGE } from '@/types/creditNote'

export class InvoiceImmutableError extends Error {
  constructor(message = CREDIT_NOTE_IMMUTABILITY_MESSAGE) {
    super(message)
    this.name = 'InvoiceImmutableError'
  }
}

/** Estados en los que la FEV ya fue emitida o radicada y no admite borrado. */
const ISSUED_ELECTRONIC_STATUSES: InvoiceStatus[] = [
  'validated',
  'submitted',
  'cuv_approved',
  'dian_sent',
  'accepted',
  'cancelled',
  'voided_by_credit_note',
]

export function isIssuedElectronicInvoice(invoice: Pick<ElectronicInvoice, 'status'>): boolean {
  return ISSUED_ELECTRONIC_STATUSES.includes(invoice.status)
}

export function isPaymentInvoiceImmutable(invoice: PaymentInvoice): boolean {
  if (invoice.status === 'voided_by_credit_note') return true
  return Boolean(invoice.invoiceNumber?.trim()) || invoice.autoGenerated === true
}

export function isPaymentInvoiceEditable(invoice: PaymentInvoice): boolean {
  return !isPaymentInvoiceImmutable(invoice)
}

export function assertPaymentInvoiceDeletable(invoice: PaymentInvoice): void {
  if (isPaymentInvoiceImmutable(invoice)) {
    throw new InvoiceImmutableError()
  }
}

export function assertElectronicInvoiceDeletable(
  invoice: Pick<ElectronicInvoice, 'status'>,
): void {
  if (invoice.status !== 'draft' && invoice.status !== 'rejected') {
    throw new InvoiceImmutableError()
  }
}

/** Campos permitidos al actualizar una FEV ya emitida (solo trazabilidad / anulación). */
const ALLOWED_ISSUED_PATCH_KEYS = new Set([
  'status',
  'cuv',
  'cufe',
  'cuvRecordId',
  'ripsJson',
  'ripsReportableTotal',
  'ripsExcludedLineCount',
  'submittedAt',
  'validatedAt',
  'rejectionReason',
  'updatedAt',
  'creditNoteId',
  'creditNoteNumber',
  'voidReason',
])

export function isAllowedIssuedElectronicInvoiceUpdate(
  previous: ElectronicInvoice,
  next: ElectronicInvoice,
): boolean {
  if (!isIssuedElectronicInvoice(previous) && previous.status !== 'rejected') {
    return true
  }

  const keys = new Set([
    ...Object.keys(previous),
    ...Object.keys(next),
  ] as Array<keyof ElectronicInvoice>)

  for (const key of keys) {
    if (ALLOWED_ISSUED_PATCH_KEYS.has(key)) continue
    if (previous[key] !== next[key]) {
      return false
    }
  }

  return true
}

export function assertElectronicInvoiceMutableUpdate(
  previous: ElectronicInvoice | undefined,
  next: ElectronicInvoice,
): void {
  if (!previous) return
  if (previous.status === 'draft' || previous.status === 'rejected') return
  if (!isAllowedIssuedElectronicInvoiceUpdate(previous, next)) {
    throw new InvoiceImmutableError(
      'No se permiten modificaciones directas sobre una factura electrónica emitida. Use Nota Crédito.',
    )
  }
}
