import type { OrthodonticsPaymentRecord, PaymentInvoice, PaymentRecord } from '@/types/clinicalRecord'
import { generateId } from '@/utils/crypto'
const INVOICE_SEQ_KEY = 'dental_emr_payment_invoice_seq'
const INVOICE_PREFIX_KEY = 'dental_emr_payment_invoice_prefix'
const DEFAULT_INVOICE_PREFIX = 'FV'

function sequenceStorageKey(userId?: string): string {
  return userId ? `${INVOICE_SEQ_KEY}_${userId}` : INVOICE_SEQ_KEY
}

export function getPaymentInvoicePrefix(): string {
  if (typeof window === 'undefined') return DEFAULT_INVOICE_PREFIX
  return localStorage.getItem(INVOICE_PREFIX_KEY)?.trim() || DEFAULT_INVOICE_PREFIX
}

export function setPaymentInvoicePrefix(prefix: string): void {
  if (typeof window === 'undefined') return
  localStorage.setItem(INVOICE_PREFIX_KEY, prefix.trim().toUpperCase() || DEFAULT_INVOICE_PREFIX)
}

/** Reserva el siguiente consecutivo de factura para Control de Pagos. */
export function reserveNextPaymentInvoiceNumber(userId?: string): string {
  const prefix = getPaymentInvoicePrefix()
  const key = sequenceStorageKey(userId)

  if (typeof window === 'undefined') {
    return `${prefix}${String(Date.now()).slice(-8)}`
  }

  const current = Number.parseInt(localStorage.getItem(key) || '0', 10)
  const next = Number.isFinite(current) ? current + 1 : 1
  localStorage.setItem(key, String(next))
  return `${prefix}${String(next).padStart(8, '0')}`
}

export interface CreateAutoPaymentInvoiceInput {
  paymentDate: string
  amount: number
  paymentReason?: string
  userId?: string
}

export function createAutoPaymentInvoice(input: CreateAutoPaymentInvoiceInput): PaymentInvoice {
  const reason = input.paymentReason?.trim()
  return {
    id: generateId(),
    invoiceNumber: reserveNextPaymentInvoiceNumber(input.userId),
    invoiceDate: input.paymentDate,
    amount: Math.max(0, input.amount || 0),
    notes: reason || 'Generada automáticamente — Control de Pagos',
    autoGenerated: true,
  }
}

type PaymentWithInvoices = {
  paymentDate: string
  amount: number
  paymentReason: string
  invoices: PaymentInvoice[]
}

export function attachAutoInvoiceToPayment<T extends PaymentWithInvoices>(
  payment: T,
  userId?: string,
): T {
  if (payment.invoices.some((invoice) => invoice.autoGenerated)) {
    return syncAutoGeneratedInvoice(payment)
  }

  return {
    ...payment,
    invoices: [
      ...payment.invoices,
      createAutoPaymentInvoice({
        paymentDate: payment.paymentDate,
        amount: payment.amount,
        paymentReason: payment.paymentReason,
        userId,
      }),
    ],
  }
}

export function syncAutoGeneratedInvoice<T extends PaymentWithInvoices>(payment: T): T {
  const autoInvoice = payment.invoices.find((invoice) => invoice.autoGenerated)
  if (!autoInvoice) return payment

  return {
    ...payment,
    invoices: payment.invoices.map((invoice) =>
      invoice.autoGenerated
        ? {
            ...invoice,
            amount: Math.max(0, payment.amount || 0),
            invoiceDate: payment.paymentDate,
          }
        : invoice,
    ),
  }
}

export function ensurePaymentsHaveAutoInvoices(
  payments: PaymentRecord[],
  userId?: string,
): PaymentRecord[] {
  return payments.map((payment) => attachAutoInvoiceToPayment(payment, userId))
}

export function ensureOrthodonticsPaymentsHaveAutoInvoices(
  payments: OrthodonticsPaymentRecord[],
  userId?: string,
): OrthodonticsPaymentRecord[] {
  return payments.map((payment) => attachAutoInvoiceToPayment(payment, userId))
}

export function paymentNeedsAutoInvoice(payment: {
  amount: number
  invoices: PaymentInvoice[]
}): boolean {
  if (!payment.amount || payment.amount <= 0) return false
  if (!payment.invoices?.length) return true
  return !payment.invoices.some((invoice) => invoice.autoGenerated)
}

export function clinicalPaymentsNeedAutoInvoices(data: {
  paymentControl?: PaymentRecord[]
  orthodonticsPaymentControl?: OrthodonticsPaymentRecord[]
}): boolean {
  const general = data.paymentControl ?? []
  const ortho = data.orthodonticsPaymentControl ?? []
  return general.some(paymentNeedsAutoInvoice) || ortho.some(paymentNeedsAutoInvoice)
}

export function normalizeClinicalRecordPayments<
  T extends {
    paymentControl?: PaymentRecord[]
    orthodonticsPaymentControl?: OrthodonticsPaymentRecord[]
  },
>(data: T, userId?: string): T {
  return {
    ...data,
    paymentControl: ensurePaymentsHaveAutoInvoices(data.paymentControl ?? [], userId),
    orthodonticsPaymentControl: ensureOrthodonticsPaymentsHaveAutoInvoices(
      data.orthodonticsPaymentControl ?? [],
      userId,
    ),
  }
}